-- select 'grant update,insert,delete on ' || table_name || ' to coldfusion_user;' from all_tables where table_name like 'CF_%';
create role coldfusion_user;
grant update,insert,delete on CF_ADDR to coldfusion_user;
grant update,insert,delete on CF_ADDRESS to coldfusion_user;
grant update,insert,delete on CF_BUGS to coldfusion_user;
grant update,insert,delete on CF_DATABASE_ACTIVITY to coldfusion_user;
grant update,insert,delete on CF_DOWNLOAD to coldfusion_user;
grant update,insert,delete on CF_GENBANK_INFO to coldfusion_user;
grant update,insert,delete on CF_LABEL to coldfusion_user;
grant update,insert,delete on CF_LOAN to coldfusion_user;
grant update,insert,delete on CF_LOAN_ITEM to coldfusion_user;
grant update,insert,delete on CF_PROJECT to coldfusion_user;
grant update,insert,delete on CF_SEARCH_RESULTS to coldfusion_user;
grant update,insert,delete on CF_TEMP_ATTRIBUTES to coldfusion_user;
grant update,insert,delete on CF_TEMP_BARCODE_PARTS to coldfusion_user;
grant update,insert,delete on CF_TEMP_CITATION to coldfusion_user;
grant update,insert,delete on CF_TEMP_CONTAINER_LOCATION to coldfusion_user;
grant update,insert,delete on CF_TEMP_LOAN to coldfusion_user;
grant update,insert,delete on CF_TEMP_LOAN_ITEM to coldfusion_user;
grant update,insert,delete on CF_TEMP_OIDS to coldfusion_user;
grant update,insert,delete on CF_TEMP_PARTS to coldfusion_user;
grant update,insert,delete on CF_TEMP_RELATIONS to coldfusion_user;
grant update,insert,delete on CF_TEMP_SCANS to coldfusion_user;
grant update,insert,delete on CF_USERS to coldfusion_user;
grant update,insert,delete on CF_USERS20060609 to coldfusion_user;
grant update,insert,delete on CF_USER_DATA to coldfusion_user;
grant update,insert,delete on CF_USER_LOAN to coldfusion_user;
grant update,insert,delete on CF_USER_LOG to coldfusion_user;
grant update,insert,delete on CF_VERSION to coldfusion_user;
grant update,insert,delete on CF_VERSION_LOG to coldfusion_user;

