create or replace view spec_with_loc as select
		HIGHER_GEOG,
			BEGAN_DATE,
			ENDED_DATE,
			VERBATIM_DATE,
			VERBATIM_LOCALITY,
			COLL_EVENT_REMARKS,
			COLLECTING_SOURCE,
			COLLECTING_METHOD,
			HABITAT_DESC,
		cataloged_item.collection_object_id,
		collecting_event.collecting_event_id,
		locality.LOCALITY_ID,
		geog_auth_rec.geog_auth_rec_id,
		MAXIMUM_ELEVATION,
		MINIMUM_ELEVATION,
		ORIG_ELEV_UNITS,
		SPEC_LOCALITY,
		LOCALITY_REMARKS,
		DEPTH_UNITS,
		MIN_DEPTH,
		MAX_DEPTH,
		NOGEOREFBECAUSE,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			ORIG_LAT_LONG_UNITS) ORIG_LAT_LONG_UNITS,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			DETERMINED_BY_AGENT_ID) DETERMINED_BY_AGENT_ID,			
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			lat_long_id) lat_long_id,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			agent_name) coordinate_determiner,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			DATUM) DATUM,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			DETERMINED_DATE) DETERMINED_DATE,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			LAT_LONG_REF_SOURCE) LAT_LONG_REF_SOURCE,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			LAT_LONG_REMARKS) LAT_LONG_REMARKS,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			MAX_ERROR_DISTANCE) MAX_ERROR_DISTANCE,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			MAX_ERROR_UNITS) MAX_ERROR_UNITS,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			NEAREST_NAMED_PLACE) NEAREST_NAMED_PLACE,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			EXTENT) EXTENT,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			GPSACCURACY) GPSACCURACY,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			GEOREFMETHOD) GEOREFMETHOD,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			gps_distance_units) gps_distance_units,
		decode(ORIG_LAT_LONG_UNITS,
			NULL,
			NULL,
			VERIFICATIONSTATUS) VERIFICATIONSTATUS,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', DEC_LAT_MIN,
			NULL) DEC_LAT_MIN,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', DEC_LONG_MIN,
			NULL) DEC_LONG_MIN,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LAT_MIN,
			'deg. min. sec.', LAT_MIN,
			NULL) LAT_MIN,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LAT_SEC,
			'deg. min. sec.', LAT_SEC,
			NULL) LAT_SEC,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LAT_DIR,
			'deg. min. sec.', LAT_DIR,
			NULL) LAT_DIR,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LONG_DEG,
			'deg. min. sec.', LONG_DEG,
			NULL) LONG_DEG,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LONG_MIN,
			'deg. min. sec.', LONG_MIN,
			NULL) LONG_MIN,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LONG_SEC,
			'deg. min. sec.', LONG_SEC,
			NULL) LONG_SEC,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LONG_DIR,
			'deg. min. sec.', LONG_DIR,
			NULL) LONG_DIR,
		decode(ORIG_LAT_LONG_UNITS,
			'degrees dec. minutes', LAT_DEG,
			'deg. min. sec.', LAT_DEG,
			NULL) LAT_DEG,
		 decode(ORIG_LAT_LONG_UNITS,
			'decimal degrees', DEC_LAT,
			NULL) DEC_LAT,
		decode(ORIG_LAT_LONG_UNITS,
			'decimal degrees', DEC_LONG,
			NULL) DEC_LONG,
		decode(ORIG_LAT_LONG_UNITS,
			'UTM', UTM_ZONE,
			NULL) UTM_ZONE,
		decode(ORIG_LAT_LONG_UNITS,
			'UTM', UTM_EW,
			NULL) UTM_EW,
		decode(ORIG_LAT_LONG_UNITS,
			'UTM', UTM_NS,
			NULL) UTM_NS
	from 
		cataloged_item,
		collecting_event,
		locality,
		geog_auth_rec,
		accepted_lat_long,
		preferred_agent_name
	where
		cataloged_item.collecting_event_id = collecting_event.collecting_event_id AND
		collecting_event.locality_id = locality.locality_id AND
		locality.geog_auth_rec_id = geog_auth_rec.geog_auth_rec_id and 
		locality.locality_id=accepted_lat_long.locality_id (+) AND
		accepted_lat_long.determined_by_agent_id = preferred_agent_name.agent_id (+) 
;
	

create or replace public synonym spec_with_loc for spec_with_loc;
grant select on spec_with_loc to public;