#! /bin/sh 
# filename: runSqlldr
# executed by cfexecute in mvzarctos application:
# http://mvzarctos.berkeley.edu/Bulkloader/bulkloaderLoader.cfm
# removes ^M from control file and loads data from external file into db

# Set variables
ORACLE_HOME=/apps/oracle/product/10.2.0
export ORACLE_HOME
NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1
export NLS_LANG

ENVRN=`/bin/domainname`
if test $ENVRN = dev
	then ORACLE_SID=mvzldev
	export ORACLE_SID
elif test $ENVRN = qa
	then ORACLE_SID=mvzlqa
	export ORACLE_SID
elif test $ENVRN = prod
	then ORACLE_SID=mvzlprod
	export ORACLE_SID
else 
	echo 'yikes! Can't set ORACLE_SID; environment isn't dev, qa, or prod!' 
	exit
fi

UAMPFILE=/users/mvzarctos/bin/.uamp
UAMP=`cat $UAMPFILE`
BULKDIR=/users/mvzarctos/tomcat/webapps/cfusion/Bulkloader
BDCTL=$BULKDIR/bulkData.ctl
BDTMP=$BULKDIR/bulkData.tmp
BDLOG=$BULKDIR/bulkData.log

# Remove ^Ms from data file.
mv $BDCTL $BDTMP
awk '{sub(/\r/,""); print}' $BDTMP > $BDCTL
rm -f $BDTMP

# Run sqlldr to load data from external file into db.
echo $UAMP | $ORACLE_HOME/bin/sqlldr uam_query@$ORACLE_SID control=$BDCTL log=$BDLOG
